### PR TITLE
Add timekit.deleteBooking method

### PR DESCRIPTION
**Pull request by donlion**
Motivation
------------
There was no support for deleting bookings

Design choices
------------
Tried to follow existing patterns

Side-effects/other
------------

Tests
------------

Known issues/limitations
------------

Release dependencies
------------

Who should review it
------------
Someone from Timekit

### CODE REVIEW

**Comment by laander** [comment]
Thank you @donlion ! I'll be merging and releasing it right away 👍

**Comment by laander** [comment]
@donlion Could you please commit and push a dummy change to the branch? CI tests wasn't enabled for forked repos, and in order to trigger it, a new commit needs to be added 🙈

**Comment by donlion** [comment]
@laander Will do! 👌

**Comment by laander** [comment]
@donlion Released in version `1.18.0`. Thanks for the contribution!

**Pull request merged**
