### PR TITLE
Update axios to v0.12.0

### PR DESCRIPTION
**Pull request by laander**
- Should enable `react-native` support and fix alot of issues
- Manually polyfilling Promises with `es6-promise` for IE support

@vistik

### CODE REVIEW

**Comment by vistik** [comment]
I must be honest I have no idea of what this means?

**Comment by laander** [comment]
@vistik A user asked if the library support `react-native` and It does, but I had to update the Axios version (the XHR lib we use) for it to support non-browser environment

**Comment by vistik** [comment]
roger 🎱 

Next time just include that comment in the description 😺

**Comment by mtt87** [comment]
👍 seems to work fine 😄 

Thanks

**Comment by laander** [comment]
@vistik @mtt87 Awesome, merging and releasing

**Pull request merged**
